name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run flake8 (линтер)
        run: flake8 .

      - name: Run black (форматтер, только проверка)
        run: black . --check

      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}/hw:${{ github.workspace }}/hw
        run: pytest hw/tests

